openapi: 3.0.0
info:
  title: Stock Reports
  version: 1.0.0

paths:
  /reports:
    get:
      tags:
        - Config
      operationId: app.get_all_report_configs
      summary: Get all report configs
      responses:
        "200":
          description: A list of reports configs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Report"
  /reports/{id}:
    get:
      tags:
        - Config
      operationId: app.get_report_config
      summary: Get a specific report config
      parameters:
        - $ref: "#/components/parameters/report_id"
      responses:
        "200":
          description: Return report config
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Report"
    put:
      tags:
        - Config
      operationId: app.put_report_config
      summary: Create or update a specific report
      parameters:
        - $ref: "#/components/parameters/report_id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Report"
      responses:
        "200":
          description: Report updated
        "201":
          description: Report created
    delete:
      tags:
        - Config
      operationId: app.delete_report_config
      summary: Delete a report config
      parameters:
        - $ref: "#/components/parameters/report_id"
      responses:
        "200":
          description: Report deleted

  /reports/{id}/data:
    get:
      tags:
        - Data
      operationId: app.get_report_data
      summary: Get data for a specific report
      parameters:
        - $ref: "#/components/parameters/report_id"
      responses:
        "200":
          description: The requested report data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ReportRow"

components:
  parameters:
    report_id:
      name: id
      in: path
      required: true
      schema:
        type: number
  schemas:
    Report:
      $ref: ./schema-report.json
    ReportRow:
      $ref: ./schema-reportrow.json
